# Generated by Django 4.1 on 2022-10-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinformation',
            name='transaction_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
