# Generated by Django 4.1 on 2022-10-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_shoppingcart_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='product_price',
            field=models.FloatField(null=True),
        ),
    ]
