# Generated by Django 4.1 on 2022-10-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_shoppingcart_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='product_subtotal',
            field=models.FloatField(null=True),
        ),
    ]
