# Generated by Django 4.1 on 2022-10-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_shoppingcart_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='product_brand',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
