# Generated by Django 4.1 on 2022-10-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(max_length=30)),
                ('product_names', models.TextField()),
                ('total_paid', models.FloatField()),
                ('card_on_file', models.CharField(max_length=16, null=True)),
                ('card_exp_date', models.DateTimeField(null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
